#!/usr/bin/env python3
"""
Build script for SBCOSInstaller.
Creates a standalone binary using PyInstaller for the current platform.
Output goes to releases/.

Usage:
    python3 build.py
"""

import os
import platform
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).parent.resolve()
RELEASES_DIR = ROOT / "releases"
VENV_DIR = ROOT / ".venv"

# Icon themes and GTK themes to keep — everything else is stripped.
KEEP_ICON_THEMES = {"hicolor", "Adwaita"}
KEEP_GTK_THEMES = {"Adwaita", "Default"}


def _in_venv():
    return sys.prefix != sys.base_prefix


def _find_system_gi():
    """Find the system gi package directory."""
    result = subprocess.run(
        [sys.executable, "-c", "import gi; print(gi.__path__[0])"],
        capture_output=True, text=True,
    )
    if result.returncode == 0:
        return Path(result.stdout.strip())
    return None


def _relaunch_in_venv():
    print("Creating clean virtual environment...")
    subprocess.check_call([
        sys.executable, "-m", "venv", str(VENV_DIR),
    ])
    if platform.system() == "Windows":
        venv_python = VENV_DIR / "Scripts" / "python.exe"
    else:
        venv_python = VENV_DIR / "bin" / "python3"

    # Symlink system gi into the clean venv so PyInstaller only bundles
    # gi and our code, not every system package.
    gi_path = _find_system_gi()
    if gi_path and gi_path.is_dir():
        venv_site = subprocess.run(
            [str(venv_python), "-c",
             "import site; print(site.getsitepackages()[0])"],
            capture_output=True, text=True,
        ).stdout.strip()
        if venv_site:
            venv_site = Path(venv_site)
            sys_site = gi_path.parent
            for pkg in ("gi", "_gi", "_gi_overrides", "pygtkcompat"):
                for item in sys_site.glob(f"{pkg}*"):
                    dest = venv_site / item.name
                    if not dest.exists():
                        dest.symlink_to(item)
                        print(f"  Linked {item.name}")
            # Link PyGObject dist-info so importlib.metadata can find it
            for item in sys_site.glob("PyGObject*.dist-info"):
                dest = venv_site / item.name
                if not dest.exists():
                    dest.symlink_to(item)
                    print(f"  Linked {item.name}")

    print(f"Re-launching build inside venv: {venv_python}")
    os.execv(str(venv_python), [str(venv_python), __file__] + sys.argv[1:])


def ensure_pyinstaller():
    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print("PyInstaller not found, installing...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "pyinstaller"])


def get_output_name():
    system = platform.system().lower()
    machine = platform.machine().lower()

    if machine in ("x86_64", "amd64"):
        machine = "x86_64"
    elif machine in ("aarch64", "arm64"):
        machine = "arm64"

    if system == "windows":
        return f"SBCOSInstaller-{machine}.exe"
    else:
        return f"SBCOSInstaller-{machine}"


def _write_spec(output_name):
    """Generate a .spec file that strips icon/theme/locale bloat."""
    separator = ";" if platform.system() == "Windows" else ":"

    add_data = ""
    if (ROOT / "resources").is_dir():
        add_data = f"('{ROOT / 'resources'}', 'resources'),"

    icon_line = ""
    if platform.system() == "Windows":
        icon_file = ROOT / "resources" / "icon.ico"
        if icon_file.exists():
            icon_line = f"icon='{icon_file}',"

    keep_icons = repr(KEEP_ICON_THEMES)
    keep_themes = repr(KEEP_GTK_THEMES)

    spec_content = textwrap.dedent(f"""\
        # Auto-generated by build.py — do not edit manually.
        import os
        import sys
        import glob

        a = Analysis(
            ['{ROOT / "main.py"}'],
            pathex=['{ROOT}'],
            hiddenimports=[
                'gi', 'gi.repository.Gtk', 'gi.repository.Gdk',
                'gi.repository.GdkPixbuf', 'gi.repository.GLib',
                'gi.repository.Pango',
            ],
            datas=[{add_data}],
        )

        # On Windows (MSYS2), collect GIO platform modules that are loaded
        # dynamically at runtime and missed by PyInstaller's import analysis.
        if sys.platform == 'win32':
            _gio_candidates = [
                '/mingw64/lib/gio/modules',
                os.path.join(os.environ.get('MSYSTEM_PREFIX', ''), 'lib', 'gio', 'modules'),
            ]
            for _gio_dir in _gio_candidates:
                if os.path.isdir(_gio_dir):
                    for _f in glob.glob(os.path.join(_gio_dir, '*.dll')):
                        a.binaries.append((os.path.join('gio', 'modules', os.path.basename(_f)), _f, 'BINARY'))
                    # Also include the module cache if present
                    _cache = os.path.join(_gio_dir, 'giomodule.cache')
                    if os.path.isfile(_cache):
                        a.datas.append((os.path.join('gio', 'modules', 'giomodule.cache'), _cache, 'DATA'))
                    break

        # Strip icon themes, GTK themes, and locale files that PyInstaller's
        # GTK hooks pull from the host system (150+ MB on a typical desktop).
        _keep_icons = {keep_icons}
        _keep_themes = {keep_themes}

        def _should_keep(name):
            parts = name.replace(os.sep, '/').split('/')
            if len(parts) >= 3 and parts[0] == 'share':
                if parts[1] == 'icons' and parts[2] not in _keep_icons:
                    return False
                if parts[1] == 'themes' and parts[2] not in _keep_themes:
                    return False
                if parts[1] == 'locale':
                    return False
            return True

        a.datas = [(name, src, typ) for name, src, typ in a.datas if _should_keep(name)]

        pyz = PYZ(a.pure)

        exe = EXE(
            pyz, a.scripts, a.binaries, a.datas,
            name='{output_name}',
            onefile=True,
            strip=False,
            console=True,
            {icon_line}
        )
    """)

    spec_path = ROOT / f"{output_name}.spec"
    spec_path.write_text(spec_content)
    return spec_path


def build():
    # Skip venv in CI — dependencies are already installed globally
    if not _in_venv() and not os.environ.get("CI"):
        _relaunch_in_venv()

    ensure_pyinstaller()

    RELEASES_DIR.mkdir(exist_ok=True)

    output_name = get_output_name()
    spec_path = _write_spec(output_name)

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--clean",
        str(spec_path),
    ]

    print(f"Building {output_name}...")
    subprocess.check_call(cmd, cwd=str(ROOT))

    built = ROOT / "dist" / output_name
    dest = RELEASES_DIR / output_name

    if dest.exists():
        dest.unlink()
    shutil.move(str(built), str(dest))

    for d in (ROOT / "build", ROOT / "dist"):
        if d.exists():
            shutil.rmtree(d)
    spec_path.unlink(missing_ok=True)

    print(f"Build complete: {dest}")
    print(f"Size: {dest.stat().st_size / (1024 * 1024):.1f} MB")


if __name__ == "__main__":
    build()
